language: shell
os: windows
git:
  depth: false
if: branch = master
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.konan/kotlin-native-windows-1.3"
script:
  - choco install jdk8
  - export JAVA_HOME='C:\Program Files\Java\jdk1.8.0_211\'
  - export GRADLE_OPTS="-Dorg.gradle.daemon=false"
  - "./gradlew.bat :build"
before_deploy:
  # TODO: Add this part to the Gradle
  - export VERSION=$(git rev-list --count HEAD)
  - git tag $VERSION
  - mv "build/bin/mingwX64/releaseExecutable/Aero.exe" "./Aero-$VERSION.exe"
deploy:
  name: ${VERSION}
  prerelease: true
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_RELEASE_KEY
  file:
    - Aero-$VERSION.exe
  on:
    repo: Trumeet/Desktop